agent:
  name: "fraud-detection-agent"
  version: "1.0.0"
  description: "AI-powered fraud detection agent for Bank of Anthos transactions"
  
# Risk Assessment Configuration
risk_thresholds:
  high_amount: 10000.0  # $10,000
  velocity_limit: 5     # transactions per time window
  time_window: 300      # seconds (5 minutes)
  
# Risk Score Thresholds
risk_levels:
  critical: 0.8
  high: 0.6
  medium: 0.4
  low: 0.0

# Bank of Anthos Service Endpoints
bank_services:
  balance_reader: "http://balancereader:8080"
  transaction_history: "http://transactionhistory:8080" 
  ledger_writer: "http://ledgerwriter:8080"
  user_service: "http://userservice:8080"
  contacts: "http://contacts:8080"

# AI Configuration
ai_config:
  project_id: "gkehackathon-472914"
  region: "us-central1"
  model: "gemini-1.5-pro"
  
# Monitoring and Alerting
monitoring:
  enable_metrics: true
  alert_webhook_url: ""
  log_level: "INFO"
  
# Agent Communication (A2A Protocol)
a2a_config:
  enable_agent_communication: true
  customer_support_agent: "http://customer-support-agent:80"
  financial_advisory_agent: "http://financial-advisory-agent:80"
  
# Security Configuration  
security:
  require_authentication: true
  jwt_verification: true
  rate_limiting:
    requests_per_minute: 100
    burst_limit: 200